// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ContractApi.Models.Base;
using System;
using System.Collections.Generic;

namespace ContractApi.Data.VO
{
    public partial class ContratosVO 
    {
        public int? Id { get; set; }
        public string NomeContrato { get; set; }
        public string Tipo { get; set; }
        public decimal Tarifa { get; set; }
        public decimal FaturamentoMax { get; set; }
        public decimal FaturamentoMin { get; set; }
        public decimal FaturamentoRealizado { get; set; }
        public decimal FaturamentoPrevisto { get; set; }
        public decimal Pld { get; set; }
        public decimal ConsumoPrevisto { get; set; }
        public decimal ConsumoRealizado { get; set; }
        public decimal VolumeContrato { get; set; }
        public string Modalidade { get; set; }
        public DateTime DataAssinatura { get; set; }
        public DateTime DataFim { get; set; }
        public DateTime DataInicio { get; set; }
        public string Status { get; set; }
    }
}