// <auto-generated />
using ContractApi.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ContractApi.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20200301012245_Contract01")]
    partial class Contract01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContractApi.Contratos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ConsumoPrevisto");

                    b.Property<decimal>("ConsumoRealizado");

                    b.Property<DateTime>("DataAssinatura");

                    b.Property<DateTime>("DataFim");

                    b.Property<DateTime>("DataInicio");

                    b.Property<decimal>("FaturamentoMax");

                    b.Property<decimal>("FaturamentoMin");

                    b.Property<decimal>("FaturamentoPrevisto");

                    b.Property<decimal>("FaturamentoRealizado");

                    b.Property<string>("Modalidade");

                    b.Property<string>("NomeContrato");

                    b.Property<decimal>("Pld");

                    b.Property<string>("Status");

                    b.Property<decimal>("Tarifa");

                    b.Property<string>("Tipo");

                    b.Property<decimal>("VolumeContrato");

                    b.HasKey("Id");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("ContractApi.Models.Empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP");

                    b.Property<string>("CNPJ");

                    b.Property<string>("Cidade");

                    b.Property<DateTime>("CriadoEm");

                    b.Property<string>("Endereco");

                    b.Property<string>("Estado");

                    b.Property<string>("InscricaEestadual");

                    b.Property<DateTime>("ModificadoEm");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
